### ISSUE TITLE
morewrites must be used after tikz/pgf and became incompatible with biblatex in 2017-04-17 update

### ISSUE THREAD

**Issue by flueterflam** [blefloch/latex-morewrites#10] opened 2017-04-19 06:22 UTC
Not sure if this affects other OSes, but I am on Windows 10.

I updated to the recent update of `morewrites` (2017-04-17 via MiKTeX package manager).  Now, I found that it and the `pgf` (or `tikz` which calls it) conflict.  Each package compiles properly on its own, but when used together, I get the error below.  There was no update related to `pgf`, so it seems likely this must be due to the `morewrites` update.

    This is XeTeX, Version 3.14159265-2.6-0.99997 (MiKTeX 2.9.6300 64-bit)
    entering extended mode
    (test-xeltx2.tex
    LaTeX2e <2017-04-15>
    Babel <3.9r> and hyphenation patterns for 75 language(s) loaded.
    ("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    ("C:\Program Files\MiKTeX 2.9\tex\latex\base\size10.clo"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\morewrites\morewrites.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\expl3.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\expl3-code.tex")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\l3xdvipdfmx.def"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\morewrites\primargs.sty"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\pgf\basiclayer\pgf.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\pgf\utilities\pgfrcs.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-common.tex"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-common-lists.te
    x")) ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-latex.def"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\ms\everyshi.sty"))
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfrcs.code.tex"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\pgf\basiclayer\pgfcore.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-cfg\graphics.cfg")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-def\xetex.def")))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\pgf\systemlayer\pgfsys.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsys.code.tex"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfkeys.code.tex"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\utilities\pgfkeysfiltered.code.te
    x")) ("C:\Program Files\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgf.cfg")
    ! Bad number (19).
    \pgfutil@IfFileExists ...feof \pgfutil@inputcheck 
                                                      #3\relax \else #2\relax \f...
    l.988 ...river file ``\pgfsysdriver'' not found.}}

This error occurs in `pdflatex` and also `xelatex`.

When try to input `morewrites` in `xetex`, I get the following error:

    ! I can't find file `morewrites'.
    l.6 \input morewrites

Let me know if I can provide additional information regarding the issue.

**Comment by flueterflam** [comment] 2017-04-19 08:56
Ok, so I have some updates about this.

First, using `\usepackage{morewrites}` AFTER `\usepackage{pgf}` and/or `\usepackage{tikz}` fixes the error mentioned above.

Second, even after doing this, there seems to be an irreconcilable conflict with the `biblatex` package.  When using `\usepackage{morewrites}` before OR after `\usepackage{biblatex}`, I receive the following error:

    ("C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\biblatex.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\logreq\logreq.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\logreq\logreq.def"))
    ("C:\Program Files\MiKTeX 2.9\tex\latex\url\url.sty")
    ! Bad number (20).
    l.1366   \ifeof\blx@bcfin

**Comment by u-fischer** [comment] 2017-04-19 09:14
I can reproduce the problem with texlive 2017 (pretest) and have shortened the problem to this example: It breaks as the closein command.

```
\documentclass{article} 
\usepackage{morewrites} 


\newread\myread 
\openin\myread=test.txt 

\closein\myread 

\begin{document} 
blub 
\end{document}
```

**Comment by blefloch** [comment] 2017-04-20 02:19
Thank you very much for reporting this.  The morewrites version 2017/04/10 is
completely broken.  I apologize and I've added tests.  Several issues

- I had added "support" for `\read` streams but forgot about the
`\ifeof` primitive, which cannot be patched; that would be needed to
allow more than 16 read streams.  So my code broke all uses of `\ifeof`,
for instance the morewrites-pgf incompatibility you encountered.  Since
it is actually hopeless to extend read streams (and no one asked me for
it) I simply deleted that code.

- While `\closeout` and `\write` correctly dealt with streams not
managed by morewrites, I had forgotten to put an analogous test in
`\openout`, which meant that the aux file was never opened.  This lead to
biblatex-morewrites incompatibility.

Ulrike's specific case was caused by a bad interaction between
`\newread` and `\wlog`, see issue #11.  It's also fixed by removing all
`\read`-related code in morewrites.

As far as I can tell this **issue is fixed**.  Please confirm.  To install
the package you can

- wait a few days for it to reach your distribution

- wait about 24 hours for it to reach CTAN and download the file
`morewrites.sty` from there (or the whole bundle, but nothing else
changed)

- compile from source, namely run TeX on `morewrites.ins` in a directory
where you've put that file plus `morewrites.dtx` and `primargs.dtx`

**Comment by blefloch** [comment] 2017-04-20 02:29
(There was also a small but important issue with a local assignment instead of a global assignment.)

**Comment by flueterflam** [comment] 2017-04-20 02:40
Great, thank you for looking into it so fast!

I compiled from source and included `\usepackage{morewrites}` at the beginning of the preamble and before/after `pgf`, `tikz`, `biblatex` includes.  Both my MWE and my longer thesis document compile without any issues related to `morewrites`.  Seems to be fixed on my end.

**Closed** 2017-04-20 18:37 UTC
Labels: bug
